import type { Metadata } from "next";
import Script from 'next/script';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "../context/AuthProvider";
import { LocaleProvider } from "../context/LocaleProvider";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="/iconfont.js" strategy="afterInteractive"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-12`}
      >
        <AuthProvider>
          <LocaleProvider>
            <Header /> {/* Header is now a Client Component */}
            {children}
          </LocaleProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
